name: youtube_player_iframe_web
description: Web implementation of webview_flutter plugin tailored for using with youtube_player_iframe package.
version: 3.1.0
homepage: https://github.com/sarbagyastha/youtube_player_flutter/tree/main/packages/youtube_player_iframe_web

environment:
  sdk: ^3.4.0
  flutter: '>=3.22.0'

flutter:
  plugin:
    implements: youtube_player_iframe
    platforms:
      web:
        pluginClass: WebYoutubePlayerIframePlatform
        fileName: src/web_youtube_player_iframe_platform.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.0.0
  webview_flutter_platform_interface: ^2.10.0

dev_dependencies:
  flutter_lints: ^4.0.0
